<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Mail;
use App\Mail\NewUserWelcomeMail;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public static function boot()
    {
        parent::boot(); // Changes the autogenerated stub

        // gets fired whenever a new user is created
        // see https://laravel.com/docs/6.x/eloquent#events
        static::created(function ($user) {

            // creates profile upon register
            $user->profile()->create([
                'title' => $user->username,
            ]);

            // send out email using https://mailtrap.io/
            // remember to add dependencies above like
            // use Illuminate\Support\Facades\Mail;
            // use App\Mail\NewUserWelcomeMail;
            Mail::to($user->email)->send(new NewUserWelcomeMail());

        });
    }

    public function posts()
    {
        return $this->hasMany(Post::class)->orderBy('created_at', 'DESC');
    }

    public function following()
    {
        return $this->belongsToMany(Profile::class);
    }

    public function profile()
    {
        return $this->hasOne(Profile::class);
    }

}
